server.name: kibana
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.requestTimeout: 90000
monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: false
xpack.reporting.enabled: true